### ISSUE TITLE
[FEATURE] Improve background design of cryptocurrencies page

### ISSUE THREAD

**Issue by kabir0x23** [CryptoverseWeb3/CryptoverseWeb3.com#11]
### Detailed description

 Improve background design of cryptocurrencies page

same design as the home page or something good you can try

### Context

![image](https://user-images.githubusercontent.com/44284877/195839004-84f9a8ac-d616-46bc-bdbc-a18c85a359b9.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Divyesh1511** [comment]
Hey @kabir0x23 can you please assign this task to me

**Comment by Hrx4** [comment]
Please assign me this issue.

**Comment by sumit-022** [comment]
I can work on this. Please assign me this issue

**Comment by kabir0x23** [comment]
Hey 

I have assigned three of you to different issues.
