### ISSUE TITLE
[FEATURE] Improve background design of NEWS page

### ISSUE THREAD

**Issue by kabir0x23** [CryptoverseWeb3/CryptoverseWeb3.com#12]
### Detailed description

Improve background design of NEWS page

![image](https://user-images.githubusercontent.com/44284877/195839341-a693d88e-4b4a-4f04-a25b-cc58df0c083c.png)

### Context

https://www.cryptoverseweb3.com/news

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srigundeti10** [comment]
@kabir0x23  Can you assign this to me please

**Comment by Hrx4** [comment]
Hey  @kabir0x23  , i can do it. Please assign me.

**Comment by kabir0x23** [comment]
Hey 

I have assigned three of you to different issues.
