### ISSUE TITLE
[FEATURE] Improve background design of Blogs page

### ISSUE THREAD

**Issue by kabir0x23** [CryptoverseWeb3/CryptoverseWeb3.com#13]
### Detailed description

Improve background design of Blogs page

![image](https://user-images.githubusercontent.com/44284877/195839497-9be40f21-9df6-4b33-a1de-f8aeede87a51.png)

### Context

https://www.cryptoverseweb3.com/blogs

### Possible implementation

same design as the home page or something good you can try

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srigundeti10** [comment]
@kabir0x23  Can you assign this to me please

**Comment by Divyesh1511** [comment]
hey, @srigundeti10 can you please assign me this task

**Comment by Divyesh1511** [comment]
hey, @kabir0x23 can you please assign this task to me

**Comment by Hrx4** [comment]
I can do it . Please assign me this issue.

**Comment by kabir0x23** [comment]
Hey 

I have assigned three of you to different issues.
