### ISSUE TITLE
[FEATURE] Add Infinite scroll

### ISSUE THREAD

**Issue by kabir0x23** [CryptoverseWeb3/CryptoverseWeb3.com#2]
### Detailed description

I suggest to add infinite scroll in news section so that the news that are not able to fit in the screen able to visible by scrolling down. 

### Context

With this feature, the news count will be increased, there is only 9-12 news on screen but with infinite scroll, user can view news as much as they want.

The infinite scroll also solves the problem of pagination. 

- Pre-loading News will slow the website for the users, so we can load the news while the user is scrolling and news will start loading so that pre-loading the news  

### Possible implementation

![image](https://user-images.githubusercontent.com/44284877/192820681-09408767-9d97-44c4-af4b-bececeb47eeb.png)

Example: loading icon while fetching the news

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Manthan-Kuber** [comment]
Hello Kabir. Can you assign me the issue so that I can work on it? My solution for implementing infinite scroll is using list virtualizer or a react windowing library.

**Comment by kabir0x23** [comment]
> Hello @kabir0x23 . Can you assign me the issue so that I can work on it? My solution for implementing infinite scroll is using list virtualizer or a react windowing library.

Hello @Manthan-Kuber , i am assigning you this issue
first: must checkout this repo: 
- https://github.com/CryptoverseWeb3/git-github-practice

**Comment by Manthan-Kuber** [comment]
> > Hello @kabir0x23 . Can you assign me the issue so that I can work on it? My solution for implementing infinite scroll is using list virtualizer or a react windowing library.
> 
> Hello @Manthan-Kuber , i am assigning you this issue first: must checkout this repo:
> 
> * https://github.com/CryptoverseWeb3/git-github-practice

Ok

**Comment by Manthan-Kuber** [comment]
@kabir0x23 I have successfully solved this issue. Please assign. Infinite scroll works flawlessly as user scrolls to 80vh. The only problem is with the layout. It's only creating a single grid column due the inf scroll component

**Comment by Manthan-Kuber** [comment]
Maybe we can do  discord/ gmeet to discuss about the same. I'll share my screen and explain the problem...

**Comment by kabir0x23** [comment]
> @kabir0x23 I have successfully solved this issue. Please assign. Infinite scroll works flawlessly as user scrolls to 80vh. The only problem is with the layout. It's only creating a single grid column due the inf scroll component

can you share a screenshot or a video something?

**Comment by kabir0x23** [comment]
> Maybe we can do discord/ gmeet to discuss about the same. I'll share my screen and explain the problem...

Yes we can.
