### ISSUE TITLE
Making this card transparent as same as crypto cards

### ISSUE THREAD

**Issue by Kritika30032002** [CryptoverseWeb3/CryptoverseWeb3.com#25]
### What would you like to share?

Making this card transparent as same as crypto cards

Assign me this

![image](https://user-images.githubusercontent.com/83400697/197198064-261e1146-f2d3-45c2-b61b-630135a2ab75.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kritika30032002** [comment]
@kabir0x23  I can only submit PR for this or other issue when my already submitted PR gets merged otherwise all the commits will be done in the same PR.

So kindly review My already submitted PR @kabir0x23

**Comment by kabir0x23** [comment]
> @kabir0x23 I can only submit PR for this or other issue when my already submitted PR gets merged otherwise all the commits will be done in the same PR.
> 
> So kindly review My already submitted PR @kabir0x23

hey @Kritika30032002 
you should create different branches for different issues.

but okay, i will merge it now after reviewing

**Comment by Kritika30032002** [comment]
Okay

But how long it takes for you to review any PR?
Just asking!!

**Comment by kabir0x23** [comment]
> Okay
> 
> But how long it takes for you to review any PR? Just asking!!

reviewed ✔
