### ISSUE TITLE
[FEATURE] Blogs page

### ISSUE THREAD

**Issue by kabir0x23** [CryptoverseWeb3/CryptoverseWeb3.com#3]
### Detailed description

Add a Blog section to the site
Can be made using React
- Add dummy data after completing this page, we will add backend later on.
### Context

Blogs plays important role in learning

### Possible implementation

Example: 👇
- Add blog nav-item under navbar
- You can make this type UI under the blog section.
- ![image](https://user-images.githubusercontent.com/44284877/192741856-58072b73-e13f-4722-a032-fc172b5dd152.png)
- website: https://www.cryptoverseweb3.com/

### Additional information

If you need any help or have questions and doubts, please ask below: 👇 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Manthan-Kuber** [comment]
Interested. Please assign.

**Comment by kabir0x23** [comment]
> @kabir0x23 I have checked the repo out. You may assign the task to me. I'll start working on the issue

Okay, I have assigned this issue to you.

**Comment by Manthan-Kuber** [comment]
@kabir0x23 The content of blog component will largely depend on the data your endpoint will be returning. What kind of dummy data do you want me to use ? I can't find any. It would be great if you could provide me some mock api of the same. For now I'll create a generic component similar to the one you have in the image above.

**Comment by kabir0x23** [comment]
> @kabir0x23 The content of blog component will largely depend on the data your endpoint will be returning. What kind of dummy data do you want me to use ? I can't find any. It would be great if you could provide me some mock api of the same. For now I'll create a generic component similar to the one you have in the image above.

Hey @Manthan-Kuber ,
You can use lorem ipsum text for filling the text and for the image use any.
After the frontend part got completed, we will connect it to the backend.

Thanks.
