### ISSUE TITLE
[FEATURE] Add dark/light Mode

### ISSUE THREAD

**Issue by kabir0x23** [CryptoverseWeb3/CryptoverseWeb3.com#8]
- Dark mode:
  - Below screenshots are in the darkmode because of an extension Dark-reader.
  - Floating dark mode toggle can be a good feature.
- Screenshots:
![image](https://user-images.githubusercontent.com/44284877/178080228-3b6618ef-cee4-4026-9fad-75d5bfda193b.png)
![image](https://user-images.githubusercontent.com/44284877/178080290-da4563cb-f022-4d8a-9fea-e57edaa41c79.png)

**Comment by Udeozor** [comment]
Hi, I would like to take this up.

**Comment by JadugarKalakaboola** [comment]
Please assign this issue to me. :)

**Comment by kabir0x23** [comment]
Hey @JadugarKalakaboola i have assigned this issue to you.

**Comment by Kritika30032002** [comment]
is this still available?

**Comment by kabir0x23** [comment]
> is this still available?

Hey @Kritika30032002 

this issue is got already solved

**Comment by kabir0x23** [comment]
you can create new issues: 
![image](https://user-images.githubusercontent.com/44284877/197187589-97fb0ce1-75e2-4162-9fad-8c1157881a34.png)

separate issues for separate errors or anything

**Comment by kabir0x23** [comment]
@Kritika30032002 
You can make this card transparent as same as crypto cards

![image](https://user-images.githubusercontent.com/44284877/197188292-aa50a658-5d7c-4df3-8e2d-d4f1650f741e.png)

**Comment by Kritika30032002** [comment]
> @Kritika30032002 You can make this card transparent as same as crypto cards
> 
> ![image](https://user-images.githubusercontent.com/44284877/197188292-aa50a658-5d7c-4df3-8e2d-d4f1650f741e.png)

okay I can @kabir0x23

**Comment by kabir0x23** [comment]
> > @Kritika30032002 You can make this card transparent as same as crypto cards
> > ![image](https://user-images.githubusercontent.com/44284877/197188292-aa50a658-5d7c-4df3-8e2d-d4f1650f741e.png)
> 
> okay I can @kabir0x23

Awesome

**Comment by Kritika30032002** [comment]
> > > @Kritika30032002 You can make this card transparent as same as crypto cards
> > > ![image](https://user-images.githubusercontent.com/44284877/197188292-aa50a658-5d7c-4df3-8e2d-d4f1650f741e.png)
> > 
> > 
> > okay I can @kabir0x23
> 
> Awesome

You can create separate issue for this and assign me that

**Comment by kabir0x23** [comment]
> You can create a separate issue for this and assign me that

Please can you create a separate issues for this, and i will assign those too you.
1. Market card new design
2. [BUG] Dark font colors are creating issues
 - you have to change the font colors, so they can be visible cleary 
 - example: https://www.cryptoverseweb3.com/crypto/Qwsogvtv82FCd 
![image](https://user-images.githubusercontent.com/44284877/197191393-d67d2e7c-6b74-4d3c-9cbe-949d84f5312a.png)

**Comment by Kritika30032002** [comment]
> > You can create a separate issue for this and assign me that
> 
> Please can you create a separate issues for this, and i will assign those too you.
> 
> 1. Market card new design
> 2. [BUG] Dark font colors are creating issues
> 
> * you have to change the font colors, so they can be visible cleary
> * example: https://www.cryptoverseweb3.com/crypto/Qwsogvtv82FCd
>   ![image](https://user-images.githubusercontent.com/44284877/197191393-d67d2e7c-6b74-4d3c-9cbe-949d84f5312a.png)

Also till then you can have a look to my PR's and merge them

1. 
https://github.com/CryptoverseWeb3/CryptoverseWeb3.com/pull/23

2. 
https://github.com/kabir0x23/MovieLand/pull/44

**Comment by Kritika30032002** [comment]
@kabir0x23

**Comment by kabir0x23** [comment]
> Also till then you can have a look to my PR's and merge them

> #23

> [kabir0x23/MovieLand#44](https://github.com/kabir0x23/MovieLand/pull/44)

Great

**Comment by Kritika30032002** [comment]
> > You can create a separate issue for this and assign me that
> 
> Please can you create a separate issues for this, and i will assign those too you.
> 
> 1. Market card new design
> 2. [BUG] Dark font colors are creating issues
> 
> * you have to change the font colors, so they can be visible cleary
> * example: https://www.cryptoverseweb3.com/crypto/Qwsogvtv82FCd
>   ![image](https://user-images.githubusercontent.com/44284877/197191393-d67d2e7c-6b74-4d3c-9cbe-949d84f5312a.png)

Also explain these issues what you actually want?
I am unable to understand first issue.

**Comment by kabir0x23** [comment]
> > @Kritika30032002 You can make this card transparent as same as crypto cards
> > ![image](https://user-images.githubusercontent.com/44284877/197188292-aa50a658-5d7c-4df3-8e2d-d4f1650f741e.png)
> 
> Also is this a separate issue?

Yes, this is.
